# Generated by Django 5.1.3 on 2025-12-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry_content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrycontent',
            old_name='parent_article',
            new_name='parent_entry_content',
        ),
    ]
