# Generated by Django 5.1.3 on 2026-02-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_content', '0002_rename_parent_article_entrycontent_parent_entry_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='content_files/content_block'),
        ),
        migrations.AlterField(
            model_name='entrycontent',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='content_files/entry_content'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='content_files/technology'),
        ),
    ]
